name: Crongen1

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  randomize-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate random cron
        id: cron
        run: |
          MIN=$((RANDOM % 60))
          HOUR=$((RANDOM % 24))
          NEW_CRON="$MIN $HOUR * * *"
          echo "new_cron=$NEW_CRON" >> $GITHUB_OUTPUT
          echo "Novo cron: $NEW_CRON"

      - name: Update workflow file
        run: |
          FILE=".github/workflows/run.yaml"
          NEW_CRON="${{ steps.cron.outputs.new_cron }}"
          sed -i "s|- cron: \".*\"|- cron: \"$NEW_CRON\"|" "$FILE"

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit updated cron
        env:
          CRONGEN_TOKEN: ${{ secrets.CRONGEN_TOKEN }}
        run: |
          git add .github/workflows/run.yaml
          git commit -m "Update cron to random time [skip ci]" || echo "No changes to commit"

          # 🔹 Reconfigura remote para usar CRONGEN_TOKEN
          git remote set-url origin "https://x-access-token:${CRONGEN_TOKEN}@github.com/${{ github.repository }}.git"

          git push origin HEAD:${{ github.ref_name }}
