name: Rewrite Author

on:
  workflow_dispatch:

jobs:
  rewrite-author:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-filter-repo
        run: |
          sudo apt update
          sudo apt install -y git-filter-repo

      - name: Overwrite author and committer
        run: |
          git filter-repo --replace-author "lorem ipsun <user@example.com>"

      - name: Push changes
        run: git push origin --force
