# This workflow does software tests when something updates
name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
    - cron: "0 15 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Export config.json
        run: |
          curl "${{ secrets.API_URL }}/config?code=${{ secrets.API_SECRET }}" -o src/config.json

      - name: Export accounts.json
        run: |
          curl "${{ secrets.API_URL }}/accounts?code=${{ secrets.API_SECRET }}" -o src/accounts.json

      # Cache Node.js deps
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Cache Playwright browsers
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      # Prepare (com deps do sistema inclusas)
      - name: Prepare
        run: |
          npm -v
          npm install
          npm run build
          npx playwright install --with-deps

      - name: Chmod Run
        run: chmod +x ./run.sh
      # Run
      - name: Run
        run: ./run.sh